# Generated by Django 2.2.4 on 2019-09-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeseries_time', models.DateTimeField()),
                ('Instantaneous_active_power', models.FloatField()),
                ('Predict_Instantaneous_active_power', models.FloatField()),
                ('Wattless_power', models.FloatField()),
                ('A_phase_current', models.FloatField()),
                ('B_phase_current', models.FloatField()),
                ('C_phase_current', models.FloatField()),
                ('A_phase_voltage', models.FloatField()),
                ('B_phase_voltage', models.FloatField()),
                ('C_phase_voltage', models.FloatField()),
                ('Total_power_factor', models.FloatField()),
                ('Forward_active_power', models.FloatField()),
                ('One_quadrant_wattless_power', models.FloatField()),
                ('Four_quadrant_wattless_power', models.FloatField()),
                ('year', models.FloatField()),
                ('month', models.FloatField()),
                ('day', models.FloatField()),
                ('hour', models.FloatField()),
                ('minute', models.FloatField()),
                ('second', models.FloatField()),
                ('dayofyear', models.FloatField()),
                ('week', models.FloatField()),
                ('dayofweek', models.FloatField()),
                ('isweekend', models.FloatField()),
                ('time_epoch', models.FloatField()),
                ('yesterday_label', models.FloatField()),
                ('last_week_label', models.FloatField()),
                ('max_last3_day_label', models.FloatField()),
                ('min_last3_day_label', models.FloatField()),
                ('mean_last3_day_label', models.FloatField()),
                ('median_last3_day_label', models.FloatField()),
                ('var_last3_day_label', models.FloatField()),
                ('max_last7_day_label', models.FloatField()),
                ('min_last7_day_label', models.FloatField()),
                ('mean_last7_day_label', models.FloatField()),
                ('median_last7_day_label', models.FloatField()),
                ('var_last7_day_label', models.FloatField()),
                ('date_day', models.DateField()),
            ],
        ),
    ]
