# Generated by Django 2.2.4 on 2019-09-04 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianbiao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='date_day',
            field=models.FloatField(default=datetime.date(2019, 9, 4)),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='day',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='dayofweek',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='dayofyear',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='hour',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='isweekend',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='last_week_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='max_last3_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='max_last7_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='mean_last3_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='mean_last7_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='median_last3_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='median_last7_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='min_last3_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='min_last7_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='minute',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='month',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='second',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='time_epoch',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='var_last3_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='var_last7_day_label',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='week',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='year',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='yesterday_label',
            field=models.FloatField(default=1),
        ),
    ]
