# Generated by Django 2.2.4 on 2019-09-04 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianbiao', '0002_auto_20190904_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='date_day',
            field=models.DateField(default=datetime.date(2019, 9, 4)),
        ),
    ]
